resource "helm_release" "kube_prometheus_stack" {
  name             = "monitoring"
  namespace        = "monitoring"
  create_namespace = true

  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "kube-prometheus-stack"
  version    = "61.0.0"

  values = [
    file("${path.module}/values.yaml")
  ]

  depends_on = [
    aws_eks_node_group.eks_node
  ]
}
